site_name: Davi Augusto Moreira Da Silva
site_author: Davi Augusto Moreira da Silva
site_description: Site pessoal de Davi Augusto Moreira da Silva
site_url: https://www.daviamsilva.dev
repo_url: https://github.com/daviamsilva/daviamsilva.dev
repo_name: daviamsilva.dev
edit_uri: edit/main/docs/
theme:
  name: material
  logo: images/Lamp2D.gif
  favicon: images/Lamp2D.gif
  icon:
    logo: fontawesome/solid/lightbulb
    repo: fontawesome/brands/github
  font:
    text: Fira Sans
    code: Fira Code
  language: pt-BR
  custom_dir: overrides
  palette:
    # Palette toggle for One Monokai
    - media: "(prefers-color-scheme: dark)"
      primary: custom
      accent: custom
      scheme: onemonokai
      toggle:
        icon: material/brightness-5
        name: One Monokai

    # Palette toggle for Automatic
    - media: "(prefers-color-scheme)"
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-auto
        name: Automático

    # Palette toggle for Light Mode
    - media: "(prefers-color-scheme: light)"
      primary: custom
      accent: custom
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Modo Claro

    # Palette toggle for Dark Mode
    - media: "(prefers-color-scheme: dark)"
      primary: custom
      accent: custom
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Modo Escuro
  features:
    # - navigation.instant
    # - navigation.footer
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top
    - content.tooltips

markdown_extensions:
  - abbr
  - tables
  - def_list
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true

watch:
  - includes/
  - overrides/

plugins:
  # Plugin desabilitado até as configurações avançadas estarem disponíveis
  # Isso é infelizmente necessário devido aos badges do shields.io
  # - privacy

  - search
  - awesome-pages
  - tags:
      tags_file: tags.md
  - blog:
      blog_toc: true
      archive_toc: true
      pagination_per_page: 5
      post_url_date_format: yyyy/MM/dd
      post_url_format: "{categories}/{slug}"
  - glightbox:
        auto_caption: true
  - git-revision-date-localized:
      type: timeago
      timezone: America/Sao_Paulo
      locale: pt
      fallback_to_build_date: false
      enable_creation_date: true
      exclude:
          - index.md
  - social:
      cards_layout_options:
        font_family: Fira Code

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: simple/whatsapp
      link: https://api.whatsapp.com/send?phone=5533988314020
      name: "WhatsApp"
    - icon: simple/linkedin
      link: https://www.linkedin.com/in/daviamsilva/
      name: "LinkedIn"
    - icon: fontawesome/solid/envelope
      link: mailto:daviamsilva@hotmail.com
      name: "E-mail"
    - icon: simple/github
      link: https://github.com/DaviAMSilva/
      name: "GitHub"
    - icon: simple/mastodon
      link: https://mastodon.social/@daviamsilva
      name: "Mastodon"
    - icon: simple/reddit
      link: https://www.reddit.com/user/DaviAMSilva/
      name: "Reddit"
    - icon: simple/lemmy
      link: https://lemmy.eco.br/u/DaviAMSilva
      name: "Lemmy"
