name: Verificar arquivos markdown
on:
  push:
    paths:
      - "**.md"
  pull_request:
    paths:
      - "**.md"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          config: .markdownlint.jsonc
          globs: |
            **.md
            !venv
